### ISSUE TITLE
Example language typescript

### ISSUE THREAD

**Issue by plaetzchen79** [tobilg/api2html#12]
Hello!
Thank you for this great project.

Is it possible to generate examples for Typescript? (eg. -l typescript)

Greetings!

**Comment by jensschneider** [comment]
I can only agree with that. That would be great.

**Comment by tobilg** [comment]
As api2html is using widdershins to render the HTML, and widdershin is using [httpsnippet](https://github.com/Kong/httpsnippet/wiki/Targets) for generating the examples, it would be necessary that `httpsnippet` would support TypeScript... It doesn't at the moment, unfortunately.
