### ISSUE TITLE
Don't see how to use customCss

### ISSUE THREAD

**Issue by gavmck** [tobilg/api2html#17]
Hey there!

Just trying this out on a project I am firing up and it's working pretty great!

One requirement I have is to add some custom CSS (or even Sass). Currently the customCss flag appears to be a boolean value of true, which is passed through to shins.

According to the shins docs

> Setting customCss to true will include the pub/css/screen_overrides.css,pub/css/print_overrides.css and pub/css/theme_override.css files, in which you can override any of the default Slate theme, to save you from having to alter the main css files directly. This should make syncing up with future Shins / Slate releases easier.

But we don't have any way to access these files as they are in node_modules using this tool.

How do I inject customCss?

Thanks!

**Comment by gavmck** [comment]
OK I have found a comment `/* Place your custom CSS overrides here */` so I'm going to try and use gulp to inject custom CSS post build.

**Comment by tobilg** [comment]
Can this issue be closed @gavmck? Thanks

**Comment by gavmck** [comment]
Yeah sure
