### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by jdtempleton** [tobilg/api2html#23]
I noticed the `customLogoUrl` CLI option isn't available on the NPM package that is published. Just curious when this might be available. 

Thanks!

**Comment by tobilg** [comment]
Thanks for the reminder, I‘ll release a nee Version tomorrow.

**Comment by jdtempleton** [comment]
Thanks! Also, I think you have a PR request that would automate this process for you. 

#14

**Comment by tobilg** [comment]
The version `0.3.4` was just released.
