### ISSUE TITLE
Restrictions always none

### ISSUE THREAD

**Issue by laiyubin** [tobilg/api2html#32]
Hi 
I am using this tool to generate a swagger 2 api document, but I cannot see any Restrictions in the generated html.
I added minLength, maxLength, I think these are restrictions.

Is this a bug? Can you give some suggestions for this problem?

**Comment by tobilg** [comment]
It should work if you define them similarly to https://github.com/Mermade/widdershins/blob/main/defs/redoc.yaml#L790-L794 (api2html uses widdershins under the hood)

**Comment by laiyubin** [comment]
@tobilg 
Thanks for you reply.

But I still cannot see restrictions in the gernerated HTML. 
I copy all  https://github.com/Mermade/widdershins/blob/main/defs/redoc.yaml to generate .
and I am using this command
`api2html -o ../../../docs/api.html    redoc.yaml`

**Comment by laiyubin** [comment]
Seems this issue is not belong to this project, it is the problem of widdershins, so close it.
