### ISSUE TITLE
theme question

### ISSUE THREAD

**Issue by braco** [tobilg/api2html#8]
edit: my bad on the error, -theme needs to be --theme

Also, it's not clear if there's a way to change the .toc-wrapper / dark parts of the theme? I'm assuming "theme" is just the middle section?

**Comment by tobilg** [comment]
--theme only changes the theme name from Highlight.js as stated in the help and in the Readme of this project.

**Comment by braco** [comment]
Thanks. Is there a clear path to making a theme flag that alters the global style? I'll make a PR if this is something viable
